/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ActiveView;

import Controller.*;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Vaibhav T
 */
public class KitchenOrderScreen extends javax.swing.JFrame {
    private Controller controller; 
    private String selectedTable; 
    /**
     * Creates new form kitchenorderpreperation
     */
    
    public KitchenOrderScreen() {
        initComponents();
      
    }
    
    public KitchenOrderScreen(Controller c, String table) {
        initComponents();
        controller = c; 
        selectedTable = table; 
    }
    public void setText(String s){
        String[] seats = s.split("%");
        
        try {
            ArrayList<String> seatOne = new ArrayList<>(Arrays.asList(seats[0].split("~")));
            ArrayList<String> seatTwo = new ArrayList<>(Arrays.asList(seats[1].split("~")));
            ArrayList<String> seatThree = new ArrayList<>(Arrays.asList(seats[2].split("~")));
            ArrayList<String> seatFour = new ArrayList<>(Arrays.asList(seats[3].split("~")));
            
            System.out.println(seatOne.toString());
            System.out.println(seatTwo.toString());
            System.out.println(seatThree.toString());
            System.out.println(seatFour.toString());
            
            
            
            String seatOneHeader = "Seat 1 \n ****************************************************************** \n";
            String seatOneOrder = ""; 

            for(int i = 0; i < seatOne.size(); i++){
                seatOneOrder += seatOne.get(i) + "\n"; 
            }


            String seatTwoHeader = "\nSeat 2 \n ****************************************************************** \n";
            String seatTwoOrder = ""; 

            for(int i = 0; i < seatTwo.size(); i++){
                seatTwoOrder += seatTwo.get(i) + "\n"; 
            }


            String seatThreeHeader = "\nSeat 3 \n ****************************************************************** \n";
            String seatThreeOrder = ""; 

            for(int i = 0; i < seatThree.size(); i++){
                seatThreeOrder += seatThree.get(i) + "\n"; 
            }


            String seatFourHeader = "\nSeat 4 \n ****************************************************************** \n";
            String seatFourOrder = ""; 

            for(int i = 0; i < seatFour.size(); i++){
                seatFourOrder += seatFour.get(i) + "\n"; 
            }
            String combinedReceipt = seatOneHeader + seatOneOrder + seatTwoHeader + seatTwoOrder + seatThreeHeader + seatThreeOrder + seatFourHeader + seatFourOrder; 

            orderList.setText(combinedReceipt);
        }
        catch(Exception e) {
            System.out.println("no active order, error was caught in kitchen order screen.");
            orderList.setText(s);
            
        }


        
        
    }
    public String getText(){
        return orderList.getText(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        finishedButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        finishedButton.setBackground(new java.awt.Color(0, 0, 0));
        finishedButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        finishedButton.setForeground(new java.awt.Color(255, 255, 0));
        finishedButton.setText("Finished");
        finishedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(orderList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(finishedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(finishedButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void finishedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedButtonActionPerformed
        
        controller.updateTableStatus(selectedTable, "ORDER READY");
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_finishedButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JButton finishedButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane orderList;
    // End of variables declaration//GEN-END:variables
}
