/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ActiveView;
import Controller.*;

/**
 *
 * @author Vaibhav T
 */
public class ManagerModule extends javax.swing.JFrame {
    private Controller controller;
    /**
     * Creates new form Managersmodule
     */
    public ManagerModule() {
       
        initComponents();
    }
    
    public ManagerModule (Controller c){
        initComponents();
        controller = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        frontEndModule = new javax.swing.JButton();
        menuManaagementModule = new javax.swing.JButton();
        payrollModule = new javax.swing.JButton();
        reportsModule = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        employeeModule1 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/restaurant-1233046.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setTitle("Manager Module");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        frontEndModule.setBackground(new java.awt.Color(0, 0, 0));
        frontEndModule.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        frontEndModule.setForeground(new java.awt.Color(255, 255, 0));
        frontEndModule.setText("Front End");
        frontEndModule.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        frontEndModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frontEndModuleActionPerformed(evt);
            }
        });

        menuManaagementModule.setBackground(new java.awt.Color(0, 0, 0));
        menuManaagementModule.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        menuManaagementModule.setForeground(new java.awt.Color(255, 255, 0));
        menuManaagementModule.setText("Menu Mangement");
        menuManaagementModule.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        menuManaagementModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManaagementModuleActionPerformed(evt);
            }
        });

        payrollModule.setBackground(new java.awt.Color(0, 0, 0));
        payrollModule.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        payrollModule.setForeground(new java.awt.Color(255, 255, 0));
        payrollModule.setText("Payroll");
        payrollModule.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        payrollModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollModuleActionPerformed(evt);
            }
        });

        reportsModule.setBackground(new java.awt.Color(0, 0, 0));
        reportsModule.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        reportsModule.setForeground(new java.awt.Color(255, 255, 0));
        reportsModule.setText("Reports");
        reportsModule.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        reportsModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsModuleActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 0));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        employeeModule1.setBackground(new java.awt.Color(0, 0, 0));
        employeeModule1.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        employeeModule1.setForeground(new java.awt.Color(255, 255, 0));
        employeeModule1.setText("Add Employees");
        employeeModule1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        employeeModule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeModule1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeModule1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuManaagementModule, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payrollModule, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frontEndModule, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(reportsModule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeModule1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payrollModule, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reportsModule, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuManaagementModule, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frontEndModule, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void payrollModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollModuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payrollModuleActionPerformed

    private void frontEndModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frontEndModuleActionPerformed
      controller.showFrontendModules();
    }//GEN-LAST:event_frontEndModuleActionPerformed

    private void reportsModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsModuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportsModuleActionPerformed

    private void menuManaagementModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManaagementModuleActionPerformed
       controller.showMenuManagement(controller);
    }//GEN-LAST:event_menuManaagementModuleActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void employeeModule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeModule1ActionPerformed
       controller.showAddEmployeeForm(controller);
    }//GEN-LAST:event_employeeModule1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeeModule1;
    private javax.swing.JButton frontEndModule;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton menuManaagementModule;
    private javax.swing.JButton payrollModule;
    private javax.swing.JButton reportsModule;
    // End of variables declaration//GEN-END:variables
}
