/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TimeClockController;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Frums
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }
    public LoginScreen(String moduleClicked, TimeClockController c) {
        initComponents();
        controller = c; 
        this.moduleClicked = moduleClicked; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        loginPadInput = new javax.swing.JTextField();
        inputKeyExit = new javax.swing.JButton();
        inputKeyEnter = new javax.swing.JButton();
        inputKeySeven = new javax.swing.JButton();
        inputKeyEight = new javax.swing.JButton();
        inputKeyNine = new javax.swing.JButton();
        inputKeyFour = new javax.swing.JButton();
        inputKeyFive = new javax.swing.JButton();
        inputKeySix = new javax.swing.JButton();
        inputKeyOne = new javax.swing.JButton();
        inputKeyTwo = new javax.swing.JButton();
        inputKeyThree = new javax.swing.JButton();
        inputKeyBackSpace = new javax.swing.JButton();
        inputKeyZero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Enter Employee ID:");
        jLabel2.setPreferredSize(new java.awt.Dimension(141, 59));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, -1));

        loginPadInput.setBorder(new javax.swing.border.MatteBorder(null));
        loginPadInput.setPreferredSize(new java.awt.Dimension(141, 59));
        loginPadInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPadInputActionPerformed(evt);
            }
        });
        getContentPane().add(loginPadInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 220, -1));

        inputKeyExit.setText("Exit");
        inputKeyExit.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyExitActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        inputKeyEnter.setText("Enter");
        inputKeyEnter.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyEnterActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        inputKeySeven.setText("7");
        inputKeySeven.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeySeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeySevenActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeySeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        inputKeyEight.setText("8");
        inputKeyEight.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyEightActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        inputKeyNine.setText("9");
        inputKeyNine.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyNineActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        inputKeyFour.setText("4");
        inputKeyFour.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyFourActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        inputKeyFive.setText("5");
        inputKeyFive.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyFiveActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        inputKeySix.setText("6");
        inputKeySix.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeySix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeySixActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeySix, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        inputKeyOne.setText("1");
        inputKeyOne.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyOneActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        inputKeyTwo.setText("2");
        inputKeyTwo.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyTwoActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        inputKeyThree.setText("3");
        inputKeyThree.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyThreeActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        inputKeyBackSpace.setText("Backspace");
        inputKeyBackSpace.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyBackSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyBackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        inputKeyZero.setText("0");
        inputKeyZero.setPreferredSize(new java.awt.Dimension(100, 100));
        inputKeyZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKeyZeroActionPerformed(evt);
            }
        });
        getContentPane().add(inputKeyZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginPadInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPadInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPadInputActionPerformed

    private void inputKeyExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_inputKeyExitActionPerformed

    private void inputKeyEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyEnterActionPerformed
        // TODO add your handling code here:
        controller.login(moduleClicked, loginPadInput.getText());
        controller.hideLoginScreen(); 
        
    }//GEN-LAST:event_inputKeyEnterActionPerformed

    private void inputKeySevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeySevenActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "7");
    }//GEN-LAST:event_inputKeySevenActionPerformed

    private void inputKeyEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyEightActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "8");
    }//GEN-LAST:event_inputKeyEightActionPerformed

    private void inputKeyNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyNineActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "9");
    }//GEN-LAST:event_inputKeyNineActionPerformed

    private void inputKeyFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyFourActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "4");
    }//GEN-LAST:event_inputKeyFourActionPerformed

    private void inputKeyFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyFiveActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "5");
    }//GEN-LAST:event_inputKeyFiveActionPerformed

    private void inputKeySixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeySixActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "6");
    }//GEN-LAST:event_inputKeySixActionPerformed

    private void inputKeyOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyOneActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "1");
    }//GEN-LAST:event_inputKeyOneActionPerformed

    private void inputKeyTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyTwoActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "2");
    }//GEN-LAST:event_inputKeyTwoActionPerformed

    private void inputKeyThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyThreeActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "3");
    }//GEN-LAST:event_inputKeyThreeActionPerformed

    private void inputKeyBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyBackSpaceActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        
        loginPadInput.setText(removeLastChar(currentText));
        
    }//GEN-LAST:event_inputKeyBackSpaceActionPerformed

    private void inputKeyZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKeyZeroActionPerformed
        // TODO add your handling code here:
        String currentText = loginPadInput.getText(); 
        loginPadInput.setText(currentText + "0");
    }//GEN-LAST:event_inputKeyZeroActionPerformed

    public JButton getButton(){
    
        return inputKeyOne; 
    }
    public String removeLastChar(String s) {
        //copy pasta from https://www.baeldung.com/java-remove-last-character-of-string :)
        return (s == null || s.length() == 0)
          ? null 
          : (s.substring(0, s.length() - 1));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }
public void showLogin(){
   new LoginScreen().setVisible(true);
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputKeyBackSpace;
    private javax.swing.JButton inputKeyEight;
    private javax.swing.JButton inputKeyEnter;
    private javax.swing.JButton inputKeyExit;
    private javax.swing.JButton inputKeyFive;
    private javax.swing.JButton inputKeyFour;
    private javax.swing.JButton inputKeyNine;
    private javax.swing.JButton inputKeyOne;
    private javax.swing.JButton inputKeySeven;
    private javax.swing.JButton inputKeySix;
    private javax.swing.JButton inputKeyThree;
    private javax.swing.JButton inputKeyTwo;
    private javax.swing.JButton inputKeyZero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loginPadInput;
    // End of variables declaration//GEN-END:variables
    private String moduleClicked; 
    private TimeClockController controller; 
}
