/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.Controller;
import Model.Database;

/**
 *
 * @author Vaibhav T
 */
public class OrderEntryScreen extends javax.swing.JFrame {

    private Controller controller;
    /**
     * Creates new form Orderenteringscreen
     */
    public OrderEntryScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        seatTwo = new javax.swing.JButton();
        seatThree = new javax.swing.JButton();
        seatOne = new javax.swing.JButton();
        seatFour = new javax.swing.JButton();
        sendToKitchen = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setForeground(new java.awt.Color(255, 255, 0));

        seatTwo.setBackground(new java.awt.Color(255, 255, 0));
        seatTwo.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        seatTwo.setText("Seat Two");
        seatTwo.setBorder(new javax.swing.border.MatteBorder(null));
        seatTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTwoActionPerformed(evt);
            }
        });

        seatThree.setBackground(new java.awt.Color(255, 255, 0));
        seatThree.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        seatThree.setText("Seat Three");
        seatThree.setBorder(new javax.swing.border.MatteBorder(null));
        seatThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatThreeActionPerformed(evt);
            }
        });

        seatOne.setBackground(new java.awt.Color(255, 255, 0));
        seatOne.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        seatOne.setText("Seat One");
        seatOne.setBorder(new javax.swing.border.MatteBorder(null));
        seatOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatOneActionPerformed(evt);
            }
        });

        seatFour.setBackground(new java.awt.Color(255, 255, 0));
        seatFour.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        seatFour.setText("Seat Four");
        seatFour.setBorder(new javax.swing.border.MatteBorder(null));
        seatFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatFourActionPerformed(evt);
            }
        });

        sendToKitchen.setBackground(new java.awt.Color(255, 255, 0));
        sendToKitchen.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        sendToKitchen.setText("Send to Kitchen");
        sendToKitchen.setBorder(new javax.swing.border.MatteBorder(null));

        payment.setBackground(new java.awt.Color(255, 255, 0));
        payment.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        payment.setText("Payment");
        payment.setBorder(new javax.swing.border.MatteBorder(null));

        save.setBackground(new java.awt.Color(255, 255, 0));
        save.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        save.setText("Save");
        save.setBorder(new javax.swing.border.MatteBorder(null));

        exit.setBackground(new java.awt.Color(255, 255, 0));
        exit.setFont(new java.awt.Font("French Script MT", 1, 24)); // NOI18N
        exit.setText("Exit");
        exit.setBorder(new javax.swing.border.MatteBorder(null));

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(seatOne, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(seatTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(seatThree, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendToKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(seatFour, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatOne, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatThree, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatFour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendToKitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // comment
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void seatOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatOneActionPerformed
        
        
        MenuList menu = new MenuList();
        menu.setVisible(true);
      
    }//GEN-LAST:event_seatOneActionPerformed

    private void seatTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTwoActionPerformed
        MenuList menu = new MenuList();
        menu.setVisible(true);
    }//GEN-LAST:event_seatTwoActionPerformed

    private void seatThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatThreeActionPerformed
       MenuList menu = new MenuList();
        menu.setVisible(true);
    }//GEN-LAST:event_seatThreeActionPerformed

    private void seatFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatFourActionPerformed
        MenuList menu = new MenuList();
        menu.setVisible(true);
    }//GEN-LAST:event_seatFourActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton payment;
    private javax.swing.JButton save;
    private javax.swing.JButton seatFour;
    private javax.swing.JButton seatOne;
    private javax.swing.JButton seatThree;
    private javax.swing.JButton seatTwo;
    private javax.swing.JButton sendToKitchen;
    // End of variables declaration//GEN-END:variables
}
