/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;

/**
 *
 * @author Owner
 */
public class Tables extends javax.swing.JPanel {

    /**
     * Creates new form Tables
     */
    public Tables() {
        initComponents();
    }    
    public Tables(TimeClockController c) {
        initComponents();
        controller = c; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableOne = new javax.swing.JButton();
        tableTwo = new javax.swing.JButton();
        tableThree = new javax.swing.JButton();
        tableSix = new javax.swing.JButton();
        tableFive = new javax.swing.JButton();
        tableFour = new javax.swing.JButton();
        tableSeven = new javax.swing.JButton();
        tableEight = new javax.swing.JButton();
        tableNine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableOne.setBackground(new java.awt.Color(0, 204, 0));
        tableOne.setText("Table 1");
        tableOne.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableOne.setPreferredSize(new java.awt.Dimension(300, 300));
        tableOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableOneActionPerformed(evt);
            }
        });
        add(tableOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tableTwo.setBackground(new java.awt.Color(0, 204, 0));
        tableTwo.setText("Table 2");
        tableTwo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableTwo.setPreferredSize(new java.awt.Dimension(300, 300));
        tableTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableTwoActionPerformed(evt);
            }
        });
        add(tableTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        tableThree.setBackground(new java.awt.Color(0, 204, 0));
        tableThree.setText("Table 3");
        tableThree.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableThree.setPreferredSize(new java.awt.Dimension(300, 300));
        tableThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableThreeActionPerformed(evt);
            }
        });
        add(tableThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        tableSix.setBackground(new java.awt.Color(0, 204, 0));
        tableSix.setText("Table 6");
        tableSix.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableSix.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        tableFive.setBackground(new java.awt.Color(0, 204, 0));
        tableFive.setText("Table 5");
        tableFive.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableFive.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        tableFour.setBackground(new java.awt.Color(0, 204, 0));
        tableFour.setText("Table 4");
        tableFour.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableFour.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        tableSeven.setBackground(new java.awt.Color(0, 204, 0));
        tableSeven.setText("Table 7");
        tableSeven.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableSeven.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, -1, -1));

        tableEight.setBackground(new java.awt.Color(0, 204, 0));
        tableEight.setText("Table 8");
        tableEight.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableEight.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, -1));

        tableNine.setBackground(new java.awt.Color(0, 204, 0));
        tableNine.setText("Table 9");
        tableNine.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        tableNine.setPreferredSize(new java.awt.Dimension(300, 300));
        add(tableNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, -1, -1));

        jLabel1.setBackground(new java.awt.Color(51, 204, 0));
        jLabel1.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel1.setText("        Ready");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 200, 210, 100));

        jLabel2.setBackground(new java.awt.Color(204, 0, 204));
        jLabel2.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel2.setText("    Order Ready");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 320, 210, 100));

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel3.setText("        Dirty");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 200, 210, 100));

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel4.setText("      Order In");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4.setOpaque(true);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, 210, 100));

        jLabel5.setBackground(new java.awt.Color(255, 255, 51));
        jLabel5.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel5.setText("    New Arrival");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 210, 100));

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setFont(new java.awt.Font("French Script MT", 0, 36)); // NOI18N
        jLabel6.setText("        Dirty");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 90, 210, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void tableOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableOneActionPerformed
        // TODO add your handling code here: read from tables and time card database tables, make a list of everyone thats currently clocked in
        // make a drop down and allow select and assignment of server. 
    }//GEN-LAST:event_tableOneActionPerformed

    private void tableTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableTwoActionPerformed

    private void tableThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableThreeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton tableEight;
    private javax.swing.JButton tableFive;
    private javax.swing.JButton tableFour;
    private javax.swing.JButton tableNine;
    private javax.swing.JButton tableOne;
    private javax.swing.JButton tableSeven;
    private javax.swing.JButton tableSix;
    private javax.swing.JButton tableThree;
    private javax.swing.JButton tableTwo;
    // End of variables declaration//GEN-END:variables
    TimeClockController controller; 
}
